# Generated by Django 5.1.4 on 2025-01-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='department',
            new_name='external_department',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='faculty',
            new_name='intenal_department',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='university',
            new_name='internal_entity',
        ),
    ]
