# Generated by Django 5.1.4 on 2025-01-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0002_rename_department_document_external_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=0.0009000900090009, max_length=100),
            preserve_default=False,
        ),
    ]
