# Generated by Django 5.1.4 on 2025-01-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0004_alter_document_document_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='ExternalDepartment',
        ),
        migrations.RemoveField(
            model_name='document',
            name='intenal_department',
        ),
        migrations.RenameModel(
            old_name='University',
            new_name='InternalEntity',
        ),
        migrations.CreateModel(
            name='InternalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('intenal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='archievesystem.internalentity')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='internal_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archievesystem.internaldepartment'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
