# Generated by Django 5.1.4 on 2025-01-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0005_rename_department_externaldepartment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internaldepartment',
            old_name='intenal_entity',
            new_name='intrenal_entity',
        ),
    ]
