# Generated by Django 5.1.4 on 2025-01-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0006_rename_intenal_entity_internaldepartment_intrenal_entity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internaldepartment',
            old_name='intrenal_entity',
            new_name='internal_entity',
        ),
    ]
