# Generated by Django 5.1.4 on 2025-02-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0007_rename_intrenal_entity_internaldepartment_internal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
